import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  fr: {
    dashboard: "Tableau de bord",
    smartAgri: "Agriculture Intelligente",
    sensorsState: "État des Capteurs",
    trends24h: "Tendances 24h",
    activeControl: "Contrôle Actif",
    activityLog: "Journal d'Activités",
    optimal: "Optimal",
    alert: "Alerte",
    updatedAt: "Mise à jour",
    tempAir: "Température air",
    humSoil: "Humidité sol",
    lux: "Luminosité",
    humAir: "Humidité air",
    waterRes: "Réserve eau",
    co2: "CO₂",
    pump: "Pompe d'irrigation",
    ventilation: "Ventilation forcée",
    led: "Éclairage LED",
    active: "Actif",
    standby: "Veille",
    manual: "Manuel",
    auto: "Automatique",
    critique: "Critique",
    warning: "Avertissement",
    info: "Info",
    logout: "Déconnexion",
    language: "Langue",
    home: "Accueil",
    actuators: "Actionneurs",
    thresholds: "Seuils",
    login: "Connexion",
    loginPortal: "Portail de gestion agricole",
    email: "Adresse Email",
    password: "Mot de passe",
    co2Excess: "CO₂ excessif détecté",
    ventAuto: "Ventilation automatique activée",
    irrigationSched: "Irrigation programmée",
    ledCycle: "Éclairage LED activé selon le cycle lumineux",
    goodMorning: "Bonjour",
    goodAfternoon: "Bon après-midi",
    goodEvening: "Bonsoir",
    temperature: "Température",
    humidity: "Humidité air",
    soilMoisture: "Humidité sol",
    light: "Luminosité",
    gaz: "Gaz",
    overview: "Vue générale",
    sensors: "Capteurs",
    alerts: "Alertes",
    activity: "Activité",
    realTime: "Temps réel",
    recent: "récentes",
    noAlerts: "Aucune alerte",
    loginError: "Erreur de connexion",
    loading: "Chargement...",
    surveillance: "Surveillance",
    historique: "Historique",
    settings: "Paramètres",
    parametres: {
      title: "Paramètres",
      subtitle: "Gérez votre profil, vos notifications et la configuration du système",
      profile: "Profil Utilisateur",
      profileSub: "Informations personnelles et professionnelles",
      fullName: "Nom Complet",
      emailAddr: "Adresse Email",
      farmName: "Nom de l'Exploitation",
      role: "Rôle Système",
      notifs: "Notifications",
      notifsSub: "Configurez comment et quand vous êtes alerté",
      channels: "Canaux de diffusion",
      emailNotif: "Alertes par Email",
      emailDesc: "Recevoir un rapport détaillé par mail",
      pushNotif: "Notifications Push",
      pushDesc: "Alertes instantanées sur le navigateur",
      levels: "Niveaux d'alerte",
      critLevel: "Critique",
      critDesc: "Dépassement dangereux des seuils",
      warnLevel: "Avertissement",
      warnDesc: "Approche des limites optimales",
      infoLevel: "Information",
      infoDesc: "Changements d'état mineurs",
      emailConfig: "Configuration Email",
      emailConfigSub: "Paramètres SMTP pour l'envoi des alertes",
      gmailAddr: "Compte Gmail",
      gmailPwd: "Mot de passe d'application",
      gmailHint: "Utilisez un mot de passe d'application Google (16 caractères)",
      recipient: "Email de réception",
      testEmail: "Tester la connexion",
      emailSent: "Email de test envoyé !",
      emailErr: "Échec de l'envoi",
      system: "Paramètres Système",
      systemSub: "Langue, fuseau horaire et rafraîchissement",
      refresh: "Fréquence de rafraîchissement",
      refreshOptions: { "1": "1 seconde", "5": "5 secondes", "15": "15 secondes", "30": "30 secondes", "60": "1 minute" },
      lang: "Langue de l'interface",
      langOptions: { "fr": "Français", "en": "English" },
      timezone: "Fuseau Horaire",
      tzOptions: { "Africa/Douala": "Cameroun (UTC+1)", "Europe/Paris": "France (UTC+2)", "UTC": "Temps Universel" },
      security: "Sécurité",
      securitySub: "Changer votre mot de passe d'accès",
      currentPw: "Mot de passe actuel",
      newPw: "Nouveau mot de passe",
      confirmPw: "Confirmer le nouveau mot de passe",
      changePw: "Mettre à jour le mot de passe",
      pwChanged: "Mot de passe modifié avec succès",
      pwRequired: "Mot de passe actuel requis",
      pwTooShort: "Le nouveau mot de passe est trop court",
      pwMismatch: "Les mots de passe ne correspondent pas",
      cancel: "Annuler les modifications",
      saveAll: "Enregistrer les modifications",
      saved: "Enregistré !",
    },
    seuilsPage: {
      rangeIn: "Plage en",
      min: "Minimum",
      max: "Maximum",
      automationRules: "🤖 Règles d'automatisation",
      ifCond: "Si",
      thenCond: "Alors :",
      activated: "Activé",
      deactivated: "Désactivé",
      addNewRule: "Ajouter une nouvelle règle",
      saveChanges: "Enregistrer les modifications",
      saving: "Enregistrement...",
      loadError: "Erreur de chargement",
      saveSuccess: "Seuils enregistrés avec succès!",
      saveError: "Erreur lors de l'enregistrement des seuils"
    },
    historiquesPage: {
      systemLog: "Journal système",
      totalAlerts: "Total alertes",
      actives: "Actives",
      resolues: "Résolues",
      noMatchingAlerts: "Aucune alerte correspondante",
      noActionsRecorded: "Aucune action enregistrée",
      turnedOn: "Allumé (ON)",
      turnedOff: "Éteint (OFF)",
      prev: "‹ Précédent",
      next: "Suivant ›",
      outOf: "sur",
      yes: "Oui",
      no: "Non"
    },
    actionneursPage: {
      equipmentControl: "Contrôle des équipements",
      manageEquipment: "Gérez vos équipements à distance en temps réel",
      activePlural: "Actifs",
      inactivePlural: "Inactifs",
      loadError: "Impossible de charger les actionneurs.",
      loadingActuators: "Chargement des actionneurs...",
      noActuators: "Aucun actionneur disponible",
      turnOff: "Éteindre",
      turnOn: "Allumer",
      cmdError: "Erreur lors de la commande de",
      scenarioError: "Erreur lors de l'exécution du scénario",
      running: "En marche",
      stopped: "Arrêté",
      quickActions: "⚡ Actions rapides",
      scenarioDesc: "Scénarios pré-configurés pour contrôler plusieurs équipements d'un coup",
      scenarios: {
        all_off: "Tout éteindre",
        all_off_sub: "Mode arrêt complet",
        night: "Mode nuit",
        night_sub: "Lampe OFF, ventilo ON",
        eco: "Économie d'énergie",
        eco_sub: "Minimum vital",
        water: "Arrosage urgent",
        water_sub: "Pompe ON immédiat"
      }
    },
    usersPage: {
      title: "Utilisateurs",
      subtitle: "Gestion des comptes et des accès",
      newUser: "+ Nouvel utilisateur",
      total: "Total",
      active: "Actifs",
      admins: "Admins",
      modifiers: "Modificateurs",
      consultation: "Consultation",
      tableUser: "UTILISATEUR",
      tableEmail: "EMAIL",
      tableRole: "RÔLE",
      tableStatus: "STATUT",
      tableCreated: "CRÉÉ LE",
      tableActions: "ACTIONS",
      noUsers: "Aucun utilisateur trouvé",
      loadError: "Impossible de charger les utilisateurs.",
      createUser: "Créer un utilisateur",
      editUser: "Modifier l'utilisateur",
      fullName: "NOM COMPLET",
      emailAddress: "ADRESSE EMAIL",
      passwordLabel: "MOT DE PASSE",
      roleLabel: "RÔLE",
      roleConsultation: "Consultation — lecture seule",
      roleModification: "Modification — peut modifier",
      roleAdmin: "Administrateur — accès total",
      pwdHintCreate: "Min. 6 caractères",
      pwdHintEdit: "Laissez vide pour ne pas changer",
      saveChanges: "Enregistrer",
      cancel: "Annuler",
      activate: "Activer",
      deactivate: "Désactiver",
      deleteMsg: "Confirmer la désactivation de cet utilisateur ?",
      statusActive: "Actif",
      statusInactive: "Inactif"
    },
    utilisateurs: "Utilisateurs",
    waterLevel: "Niveau d'eau",
    high: "HAUT",
    low: "BAS",
    levelOk: "Niveau OK",
    levelLow: "Niveau bas",
    saveSuccess: "Seuils enregistrés avec succès !",
    saveError: "Erreur lors de l'enregistrement des seuils",
    thresholdTitle: "Seuils",
    thresholdSubtitle: "Définissez les limites pour vos capteurs",
    actuatorTitle: "Actionneurs",
    actuatorSubtitle: "Contrôlez vos équipements à distance",
    historyTitle: "Historique",
    historySubtitle: "Alertes déclenchées et actions enregistrées",
    resolve: "Résoudre",
    exportCSV: "Exporter CSV",
    refresh: "Actualiser",
    all: "Toutes",
    resolved: "Résolues",
    noData: "Aucune donnée",
    pumpName: "Pompe à eau",
    pumpType: "Distribution d'eau",
    lampName: "Lampes de croissance",
    lampType: "Éclairage LED",
    ventName: "Ventilateurs",
    ventType: "Circulation d'air",
    irrigationName: "Système d'irrigation",
    irrigationType: "Arrosage automatique",
    equipment: "Équipement",
    on: "ON",
    off: "OFF",
    min: "Min",
    max: "Max",
    enabled: "Activé",
    disabled: "Désactivé",
    status: "Statut",
    type: "Type",
    name: "Nom",
    value: "Valeur",
    threshold: "Seuil",
    save: "Enregistrer",
    reset: "Réinitialiser",
    cancel: "Annuler",
    confirm: "Confirmer",
    total: "Total",
    actions: "Actions",
    actionLog: "Journal d'actions",
    alertLog: "Journal d'alertes",
    from: "De",
    to: "À",
    date: "Date",
    time: "Heure",
    message: "Message",
    source: "Source",
    autoMode: "Automatique",
    manualMode: "Manuel",
    remote: "À distance",
    system: "Système",
  },
  en: {
    dashboard: "Dashboard",
    smartAgri: "Smart Agriculture",
    sensorsState: "Sensors Status",
    trends24h: "24h Trends",
    activeControl: "Active Control",
    activityLog: "Activity Log",
    optimal: "Optimal",
    alert: "Alert",
    updatedAt: "Updated at",
    tempAir: "Air Temperature",
    humSoil: "Soil Humidity",
    lux: "Luminosity",
    humAir: "Air Humidity",
    waterRes: "Water Reserve",
    co2: "CO₂",
    pump: "Irrigation Pump",
    ventilation: "Forced Ventilation",
    led: "LED Lighting",
    active: "Active",
    standby: "Standby",
    manual: "Manual",
    auto: "Auto",
    critique: "Critical",
    warning: "Warning",
    info: "Info",
    logout: "Logout",
    language: "Language",
    home: "Home",
    actuators: "Actuators",
    thresholds: "Thresholds",
    login: "Login",
    loginPortal: "Agricultural management portal",
    email: "Email Address",
    password: "Password",
    co2Excess: "Excessive CO₂ detected",
    ventAuto: "Automatic ventilation activated",
    irrigationSched: "Irrigation scheduled",
    ledCycle: "LED lighting activated per light cycle",
    goodMorning: "Good morning",
    goodAfternoon: "Good afternoon",
    goodEvening: "Good evening",
    temperature: "Temperature",
    humidity: "Air Humidity",
    soilMoisture: "Soil Moisture",
    light: "Luminosity",
    gaz: "Gas",
    overview: "Overview",
    sensors: "Sensors",
    alerts: "Alerts",
    activity: "Activity",
    realTime: "Real-time",
    recent: "recent",
    noAlerts: "No alerts",
    loginError: "Login error",
    loading: "Loading...",
    surveillance: "Monitoring",
    historique: "History",
    settings: "Settings",
    parametres: {
      title: "Settings",
      subtitle: "Manage your profile, notifications and system configuration",
      profile: "User Profile",
      profileSub: "Personal and professional information",
      fullName: "Full Name",
      emailAddr: "Email Address",
      farmName: "Farm Name",
      role: "System Role",
      notifs: "Notifications",
      notifsSub: "Configure how and when you are alerted",
      channels: "Notification channels",
      emailNotif: "Email Alerts",
      emailDesc: "Receive a detailed report by email",
      pushNotif: "Push Notifications",
      pushDesc: "Instant alerts on the browser",
      levels: "Alert levels",
      critLevel: "Critical",
      critDesc: "Dangerous threshold crossing",
      warnLevel: "Warning",
      warnDesc: "Approaching optimal limits",
      infoLevel: "Information",
      infoDesc: "Minor state changes",
      emailConfig: "Email Configuration",
      emailConfigSub: "SMTP settings for sending alerts",
      gmailAddr: "Gmail Account",
      gmailPwd: "App Password",
      gmailHint: "Use a Google App Password (16 characters)",
      recipient: "Recipient Email",
      testEmail: "Test Connection",
      emailSent: "Test email sent!",
      emailErr: "Failed to send",
      system: "System Settings",
      systemSub: "Language, timezone and refresh rate",
      refresh: "Refresh frequency",
      refreshOptions: { "1": "1 second", "5": "5 seconds", "15": "15 seconds", "30": "30 seconds", "60": "1 minute" },
      lang: "Interface Language",
      langOptions: { "fr": "French", "en": "English" },
      timezone: "Timezone",
      tzOptions: { "Africa/Douala": "Cameroon (UTC+1)", "Europe/Paris": "France (UTC+2)", "UTC": "Universal Time" },
      security: "Security",
      securitySub: "Change your access password",
      currentPw: "Current Password",
      newPw: "New Password",
      confirmPw: "Confirm New Password",
      changePw: "Update Password",
      pwChanged: "Password successfully changed",
      pwRequired: "Current password required",
      pwTooShort: "New password is too short",
      pwMismatch: "Passwords do not match",
      cancel: "Cancel changes",
      saveAll: "Save changes",
      saved: "Saved!",
    },
    seuilsPage: {
      rangeIn: "Range in",
      min: "Minimum",
      max: "Maximum",
      automationRules: "🤖 Automation Rules",
      ifCond: "If",
      thenCond: "Then:",
      activated: "Enabled",
      deactivated: "Disabled",
      addNewRule: "Add new rule",
      saveChanges: "Save changes",
      saving: "Saving...",
      loadError: "Loading error",
      saveSuccess: "Thresholds saved successfully!",
      saveError: "Error saving thresholds"
    },
    historiquesPage: {
      systemLog: "System Log",
      totalAlerts: "Total alerts",
      actives: "Active",
      resolues: "Resolved",
      noMatchingAlerts: "No matching alerts",
      noActionsRecorded: "No recorded actions",
      turnedOn: "Turned On (ON)",
      turnedOff: "Turned Off (OFF)",
      prev: "‹ Previous",
      next: "Next ›",
      outOf: "of",
      yes: "Yes",
      no: "No"
    },
    actionneursPage: {
      equipmentControl: "Equipment Control",
      manageEquipment: "Manage your equipment remotely in real-time",
      activePlural: "Active",
      inactivePlural: "Inactive",
      loadError: "Unable to load actuators.",
      loadingActuators: "Loading actuators...",
      noActuators: "No actuators available",
      turnOff: "Turn off",
      turnOn: "Turn on",
      cmdError: "Error controlling",
      scenarioError: "Error executing scenario",
      running: "Running",
      stopped: "Stopped",
      quickActions: "⚡ Quick Actions",
      scenarioDesc: "Pre-configured scenarios to control multiple devices at once",
      scenarios: {
        all_off: "Turn all off",
        all_off_sub: "Complete shutdown mode",
        night: "Night mode",
        night_sub: "Lamp OFF, fan ON",
        eco: "Energy saving",
        eco_sub: "Bare minimum",
        water: "Urgent watering",
        water_sub: "Immediate pump ON"
      }
    },
    usersPage: {
      title: "Users",
      subtitle: "Account and access management",
      newUser: "+ New user",
      total: "Total",
      active: "Active",
      admins: "Admins",
      modifiers: "Modifiers",
      consultation: "Consultation",
      tableUser: "USER",
      tableEmail: "EMAIL",
      tableRole: "ROLE",
      tableStatus: "STATUS",
      tableCreated: "CREATED AT",
      tableActions: "ACTIONS",
      noUsers: "No users found",
      loadError: "Unable to load users.",
      createUser: "Create a user",
      editUser: "Edit user",
      fullName: "FULL NAME",
      emailAddress: "EMAIL ADDRESS",
      passwordLabel: "PASSWORD",
      roleLabel: "ROLE",
      roleConsultation: "Consultation — read only",
      roleModification: "Modification — can modify",
      roleAdmin: "Administrator — full access",
      pwdHintCreate: "Min. 6 characters",
      pwdHintEdit: "Leave empty to keep unchanged",
      saveChanges: "Save",
      cancel: "Cancel",
      activate: "Activate",
      deactivate: "Deactivate",
      deleteMsg: "Confirm deactivation of this user?",
      statusActive: "Active",
      statusInactive: "Inactive"
    },
    utilisateurs: "Users",
    waterLevel: "Water Level",
    high: "HIGH",
    low: "LOW",
    levelOk: "Level OK",
    levelLow: "Low level",
    saveSuccess: "Thresholds saved successfully!",
    saveError: "Error saving thresholds",
    thresholdTitle: "Thresholds",
    thresholdSubtitle: "Set limits for your sensors",
    actuatorTitle: "Actuators",
    actuatorSubtitle: "Control your equipment remotely",
    historyTitle: "History",
    historySubtitle: "Triggered alerts and recorded actions",
    resolve: "Resolve",
    exportCSV: "Export CSV",
    refresh: "Refresh",
    all: "All",
    resolved: "Resolved",
    noData: "No data",
    pumpName: "Water Pump",
    pumpType: "Water Distribution",
    lampName: "Growth Lamps",
    lampType: "LED Lighting",
    ventName: "Fans",
    ventType: "Air Circulation",
    irrigationName: "Irrigation System",
    irrigationType: "Automatic Watering",
    equipment: "Equipment",
    on: "ON",
    off: "OFF",
    min: "Min",
    max: "Max",
    enabled: "Enabled",
    disabled: "Disabled",
    status: "Status",
    type: "Type",
    name: "Name",
    value: "Value",
    threshold: "Threshold",
    save: "Save",
    reset: "Reset",
    cancel: "Cancel",
    confirm: "Confirm",
    total: "Total",
    actions: "Actions",
    actionLog: "Action Log",
    alertLog: "Alert Log",
    from: "From",
    to: "To",
    date: "Date",
    time: "Time",
    message: "Message",
    source: "Source",
    autoMode: "Automatic",
    manualMode: "Manual",
    remote: "Remote",
    system: "System",
  }
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(localStorage.getItem('appLang') || 'fr');

  useEffect(() => {
    localStorage.setItem('appLang', lang);
  }, [lang]);

  const t = (key) => {
    const val = translations[lang][key];
    if (typeof val === 'string') return val;
    return val || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, switchLang: setLang, t, tObj: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
